# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build_and_push:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run :
          name: Build Docker Image and Push to Docker hub
          command: /
            docker login -u "$DOCKERUBH_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker build -t hooo0503/test:latest
            docker push hooo0503/test:latest
  deploy:
    docker:
      - image: apsgroup/awscli-sls
    steps:
      - checkout
      - run:
          name: Deploy to ECS
          command: |
            chmod +x ./.circleci/deploy.sh
            bash ./.circleci/deploy.sh

workflows:
  automatic_deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      #- build_and_push:
      #    filters:
      #      branches:
      #        only: circle
      - deploy:
          filters:
            branches:
              only: circle
        #  requires:
        #      - build_and_push
